version: '3.7'

services: 
  mongodb: 
    image: mongo
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: lifeorganizer
    ports: 
      - '27017:27017'